dubbo:
  application:
    id: jdy-admin
    name: jdy-admin
    qos-enable: false
  registry:
    id: jdy
    protocol: zookeeper
    address: 127.0.0.1:2181
pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据 #    address: 106.13.122.154:2181      #    address: 127.0.0.1:2181
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
spring:
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 60.205.218.186
    port: 6379
    max-active: 100 #连接池最大连接数
    max-wait: 30000 #最大阻塞时间
    max-idle: 20 #连接池的最大空闲连接
    min-idle: 0  #连接池的最小控线连接
    timeout: 10000 #连接超时
  activemq:
    in-memory: false
    broker-url: tcp://192.168.80.1:61616
    user: admin
    password: admin
my_queue: boot-active-queue