server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://kong01.com:7001/eureka/,http://kong02.com:7002/eureka/,http://kong03.com:7003/eureka/
