server:
  port: 2020
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
service:
  version: 1.0
spring:
  application:
    name: jdy-service
  profiles:
    active: test
  messages:
    encoding: UTF-8
    basename: i18n/messages